gnwproject/urls.py
#import debug_toolbar
from django.conf.urls import url, include
from django.contrib import admin
from gnw import views as gnw_views
from sms import views as sms_views
from people import views as people_views
from django.urls import path


urlpatterns = [
    url(r'^ycchtliaaau/', admin.site.urls, name='admin-page'),
    url(r'^admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += [
    url(r'^$', gnw_views.index, name='index'),
    #url(r'^signup/$', sms_views.signup_captcha, name='signup'), Turned off since we are not allowing direct user signups
    #url(r'^signup/activate/(?P<token>\w+)/$', sms_views.activate_new_user, name='activate_new_user'),
    url(r'^panel/$', gnw_views.panel, name='panel'),
    url(r'^panel/update_my_info/$', people_views.update_student_info, name='update_student_info'),
    url(r'^panel/show_my_info/$', people_views.show_my_info, name='show_my_info'),
    url(r'^course/(?P<slug>[\w-]+)/$', gnw_views.course, name='class'),
    url(r'^course/(?P<slug>[\w-]+)/video/(?P<uuid>\d+)/$', gnw_views.video, name='video'),
    url(r'^course/(?P<slug>[\w-]+)/quiz/(?P<uuid>\d+)/$', gnw_views.quiz, name='quiz'),
    url(r'^course/(?P<slug>[\w-]+)/assignment/(?P<uuid>\d+)/$', gnw_views.assignment, name='assignment'),
]

urlpatterns += [
    url(r'^api/submit-photo-assignment/', gnw_views.submit_image_assignment, name='submit-photo-assignment'),
]

#Ajax to request sms sign-up verification
urlpatterns += [
    url(r'^ajax/request_sms/(?P<token>\w+)/$', sms_views.ajax_send_sms_verification_code, name='ajax_send_sms_verification_code'),
]

#Request sms verification for password reset, etc. 
urlpatterns += [
    url(r'^reset_password_request/$', sms_views.reset_password_captcha, name='reset_password_captcha'),
    url(r'^reset_password_sms/(?P<token>\w+)/$', sms_views.reset_password_sms, name='reset_password_sms'),
    url(r'^reset_password_confirm/(?P<token>\w+)/$', sms_views.reset_password_confirm, name='reset_password_confirm'),
    url(r'^require-password-change/$', sms_views.require_password_change, name='require_password_change'),
]

urlpatterns += [
    url(r'^progress/', include('progress.urls')),
]

urlpatterns += [
    url(r'^captcha/', include('captcha.urls')),
    #path('__debug__/', include(debug_toolbar.urls)),
]

progress/urls.py
from django.conf.urls import url
from progress import views

urlpatterns = [
    url(r'^ajax/record_completed_lesson/$', views.ajax_record_completed_lesson, name='record_completed_lesson'),
]

sms/models.py
from django.db import models

#======================================================
#SMS Code
#======================================================
class SMS_Code(models.Model):
    """
    The code is a 7-digit numeric sequence using digits
    0-9. As such, there are ten million possibilities.
    The "tries" field helps to protect against brute force
    guessing. Currently, in the view, the threshhold is set at 3.
    After 3 guesses, this sms code is voided and the user must
    get another one for this mobile number. This means
    there is only a probability of 3 in 10 million that an attacker
    will guess the code correctly.
    """
    mobile = models.CharField(max_length = 25)
    code = models.CharField(max_length = 7)
    created = models.DateTimeField()
    verified = models.BooleanField(default=False)
    expired = models.BooleanField(default=False)
    tries = models.PositiveSmallIntegerField(default=0)

    def __str__(self):
        return self.mobile

class Token(models.Model):
    """
    This token is used to reset user passwords.
    This has to be used during the same session, that is
    if the user logs out and then logs back in, this
    token is voided. The "created" field is used to set
    a further restriction on by when it must be used.
    """
    mobile = models.CharField(max_length = 25)
    session_key = models.CharField(null=False, max_length=40)
    token_hex_str = models.CharField(max_length = 32)
    created = models.DateTimeField()
    verified = models.BooleanField(default=False)
    expired = models.BooleanField(default=False)

    def __str__(self):
        return self.token_hex_str


class Registration_Token(models.Model):
    """
    This token is used to activate new users. It is used
    in the one-time url to submit SMS verification code,
    as well as in the url used by AJAX to request the
    SMS code. Unlike the above token, it does not track
    the user session, which is not available to inactive users.
    """
    mobile = models.CharField(max_length = 25)
    token_hex_str = models.CharField(max_length = 32)
    created = models.DateTimeField()
    sms_sent = models.PositiveSmallIntegerField(default=0)
    verified = models.BooleanField(default=False)
    expired = models.BooleanField(default=False)

    def __str__(self):
        return self.token_hex_str

sms/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from people.models import CustomUser
from captcha.fields import CaptchaField
import re


class CaptchaScreenForm(forms.Form):
    mobile = forms.CharField(max_length=11, min_length=11)
    captcha = CaptchaField()

    def clean_mobile(self):
        #This is the clean function for the 'mobile' field specifically
        #It does custom validation for the 'mobile' field
        mobile_number = self.cleaned_data['mobile']
        try:
            mobile_number_str = str(mobile_number)
        except ValueError:
            return mobile_number
        #Use regex to verify this is a China mobile number
        #(1): It starts with '1'
        #(2): It is consisted of all digits
        #(3): It has exactly 11 digits
        if re.match(r'^[1][0-9]{10}$', mobile_number_str):
            return mobile_number
        else:
            raise forms.ValidationError("请输入一个有效的手机号码")

    
class SignUpForm(UserCreationForm):
    """
    This form is not used currently. We are not allowing users to sign up on the website. 
    Users get signed up by us when they purchase our courses on the third-party ecommerce platform.
    """
    verification_code = forms.CharField(max_length=7, min_length=7)

    class Meta:
        model = CustomUser
        fields = ('username', 'mobile', 'password1', 'password2')


class RequestSMSCodeForm(forms.Form):
    verification_code = forms.CharField(max_length=6, min_length=6)

    

sms/views.py
from uuid import uuid4
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST
from django.utils import timezone
from django.utils.crypto import get_random_string
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth import login, authenticate, update_session_auth_hash, get_user_model
from django.contrib.auth.forms import SetPasswordForm
from django.contrib.auth.decorators import login_required
from django.urls import reverse
#from django.core.mail import mail_managers
from django.db.models import F
from .models import SMS_Code, Token, Registration_Token
from .forms import SignUpForm, RequestSMSCodeForm, CaptchaScreenForm
from .helpers import send_sms



User = get_user_model()

#Templates:
#--------------------------------------
signup_captcha_template = 'sms/signup_captcha.html'
activate_new_user_template = 'sms/activate_new_user.html'
reset_password_captcha_template = 'sms/reset_password_captcha.html'
reset_password_sms_template = 'sms/reset_password_sms.html'
reset_password_template = 'sms/reset_password.html'
require_password_change_template = 'sms/require_password_change.html'
#--------------------------------------

template_context = {}

def signup_captcha(request):
    """
    This function is not used currently. The url that routes to this view function is disabled, as 
    we are not allowing users to sign up on the website. Users get signed up by us when they purchase
    our courses on the third-party ecommerce platform.
    """
    if request.user.is_authenticated:
        return redirect(reverse('panel'))
    if request.method == 'POST':
        form = CaptchaScreenForm(request.POST)
        if form.is_valid():
            mobile_number = form.cleaned_data.get('mobile')
            if User.objects.filter(mobile = mobile_number).exists():
                template_context.update({'form': form, 'mobile_already_registered':True})
                return render(request, signup_captcha_template, template_context)
            else:
                token_string = str(uuid4().hex)
                Registration_Token.objects.create(mobile=mobile_number, token_hex_str=token_string, created = timezone.now())
                return redirect(reverse('activate_new_user', kwargs={'token': token_string}))
        else:
            template_context.update({'form': form})
            return render(request, signup_captcha_template, template_context)
    else:
        form = CaptchaScreenForm()
        template_context.update({'form': form})
        return render(request, signup_captcha_template, template_context)


def activate_new_user(request, token):
    """
    This function is not used currently. The url that routes to this view function is disabled, as 
    we are not allowing users to sign up on the website. Users get signed up by us when they purchase
    our courses on the third-party ecommerce platform.
    """
    registration_token = Registration_Token.objects.filter(token_hex_str=token, verified=False, expired=False, sms_sent__lte=3).order_by('-created').first()
    if registration_token is None:
        return redirect(reverse('signup'))
    else:
        if (timezone.now() - registration_token.created).total_seconds() > 600: #Consider using F() and timedelta(seconds=xxx)
            return redirect(reverse('signup'))
    if request.method != 'POST':
        form = SignUpForm()
        template_context.update({'form': form, 'token_hex_str':token, 'mobile':registration_token.mobile})
        return render(request, activate_new_user_template, template_context)
    else:
        form = SignUpForm(request.POST)
        if form.is_valid():
            try:
                hidden_mobile_field_tampered_with = str(registration_token.mobile).strip() != str(form.cleaned_data.get('mobile')).strip()
            except ValueError:
                return redirect(reverse('signup'))
            else:
                if hidden_mobile_field_tampered_with:
                    return redirect(reverse('signup'))
                
            sms = SMS_Code.objects.filter(mobile=registration_token.mobile, verified=False, expired=False, tries__lt=3).order_by('-created').first()
            if sms is None:
                template_context['form'] = form
                template_context['token_hex_str'] = token
                template_context['mobile'] = registration_token.mobile
                template_context['sms_authentication_failed'] = True
                return render(request, activate_new_user_template, template_context)
            if sms.code != form.cleaned_data.get('verification_code'):
                sms.tries = F('tries') + 1
                sms.save()
                template_context['form'] = form
                template_context['token_hex_str'] = token
                template_context['mobile'] = registration_token.mobile
                template_context['sms_authentication_failed'] = True
                return render(request, activate_new_user_template, template_context)
            if (timezone.now() - sms.created).total_seconds() > 90: #Consider using F() and timedelta(seconds=xxx)
                template_context['form'] = form
                template_context['token_hex_str'] = token
                template_context['mobile'] = registration_token.mobile
                template_context['sms_authentication_failed'] = True
                return render(request, activate_new_user_template, template_context)
            #if User.objects.filter(username = registration_token.mobile).exists():
                #return redirect(reverse('signup'))
            else:
                form.save()
                raw_password = form.cleaned_data.get('password1')
                username = form.cleaned_data.get('username')
                new_user = authenticate(username=username, password=raw_password) 
                if new_user is not None:
                    login(request, new_user)
                else:
                    return redirect(reverse('signup'))
                sms.verified = True
                sms.save()
                registration_token.verified = True
                registration_token.save()
                messages.success(request, '欢迎加入飞猫星球!')
                #mail_managers(
                #    'New User Registration; ' + 'Time: ' + str(timezone.now()),
                #    'User mobile: ' + str(registration_token.mobile),
                #)
                return redirect(reverse('panel'))
        else:
            template_context['form'] = form
            template_context['token_hex_str'] = token
            template_context['mobile'] = registration_token.mobile
            return render(request, activate_new_user_template, template_context)


def reset_password_captcha(request):
    if request.user.is_authenticated:
        return redirect(reverse('panel'))
    if request.method == 'POST':
        form = CaptchaScreenForm(request.POST)
        if form.is_valid():
            mobile_number = form.cleaned_data.get('mobile')
            #Is below the best option to avoid leaking information?
            if not User.objects.filter(mobile = mobile_number).exists():
                template_context.update({'form': form})
                return render(request, reset_password_captcha_template, template_context)
            else:
                token_string = str(uuid4().hex)
                Registration_Token.objects.create(mobile=mobile_number, token_hex_str=token_string, created = timezone.now())
                return redirect(reverse('reset_password_sms', kwargs={'token': token_string}))
        else:
            template_context.update({'form': form})
            return render(request, reset_password_captcha_template, template_context)
    else:
        form = CaptchaScreenForm()
        template_context.update({'form': form})
        return render(request, reset_password_captcha_template, template_context)


def reset_password_sms(request, token):
    registration_token = Registration_Token.objects.filter(token_hex_str=token, verified=False, expired=False, sms_sent__lte=3).order_by('-created').first()
    if registration_token is None:
        return redirect(reverse('reset_password_captcha'))
    else:
        if (timezone.now() - registration_token.created).total_seconds() > 600: #Consider using F() and timedelta(seconds=xxx)
            return redirect(reverse('reset_password_captcha'))
    if request.method != 'POST':
        form = RequestSMSCodeForm()
        template_context.update({'form': form, 'token_hex_str':token, 'mobile':registration_token.mobile})
        return render(request, reset_password_sms_template, template_context)
    else:
        form = RequestSMSCodeForm(request.POST)
        if form.is_valid():                
            sms = SMS_Code.objects.filter(mobile=registration_token.mobile, verified=False, expired=False, tries__lt=3).order_by('-created').first()
            if sms is None:
                template_context['form'] = form
                template_context['token_hex_str'] = token
                template_context['mobile'] = registration_token.mobile
                template_context['sms_authentication_failed'] = True
                return render(request, reset_password_sms_template, template_context)
            if (timezone.now() - sms.created).total_seconds() > 90: #Consider using F() and timedelta(seconds=xxx)
                template_context['form'] = form
                template_context['token_hex_str'] = token
                template_context['mobile'] = registration_token.mobile
                template_context['sms_authentication_failed'] = True
                return render(request, reset_password_sms_template, template_context)
            if sms.code != form.cleaned_data.get('verification_code'):
                sms.tries = F('tries') + 1
                sms.save()
                template_context['form'] = form

sms/templates/sms/activate_new_user.html
{% extends 'base_generic.html' %}

{% load static %}

{% block content %}

    {% if sms_authentication_failed %}
        <div class="loginErrorMessageDiv">短信验证失败。请您确认您填写的手机号码，然后再获取一个新的验证码试一次。如您需要帮助，请联系我们。</div>
    {% endif %}

    {% if form.errors %}
        {% for key,value in form.errors.items %} 
            <div class="loginErrorMessageDiv">{{ value }}</div>
        {% endfor %}
    {% endif %}

    <div id="signupFormWrapper">
        <div id="loginFormCardTitle" class="d-flex justify-content-center align-items-center">
            <div></div>
        </div>
        <form class="loginForm" method="post" action="{% url 'activate_new_user' token=token_hex_str %}">
        {% csrf_token %}
            <div class="studentInfoItem" id="signupMobile">
              <span>手机号码： </span>{{ mobile }}
            </div>
            <input id='id_mobile' name='mobile' type='hidden' value='{{mobile}}'>
            <div class="loginInputDiv" id="usernameInputDiv">
              <label for="{{ form.username.id_for_label }}">用户名 </label>{{ form.username }}
            </div>
            <div class="loginInputDiv" id="password1InputDiv">
              <label for="{{ form.password1.id_for_label }}">密码 </label>{{ form.password1 }}
            </div>
            <div class="loginInputDiv" id="password2InputDiv">
              <label for="{{ form.password2.id_for_label }}">确认密码 </label>{{ form.password2 }}
            </div>
            <div class="loginInputDiv" id="smsVerificationCodeDiv">
              <label for="{{ form.verification_code.id_for_label }}">短信验证码 </label>{{ form.verification_code }}<div id="smsBtn">获取验证码</div>
            </div>
            <div>
              <button type="submit" class="loginPageButton">确认</button>
            </div>
        </form>
        <div id="loginFormLinktoSignup" class="d-flex justify-content-center align-items-center">
            <div>已经有账号？<a href="{% url 'login'%}"><span>立即登录</span></a></div>
        </div>
    </div>

{% endblock %}

{% block body-internal-js %}
    <script>var for_signup_django = true;</script>
    <script>var token_django = '{{token_hex_str}}';</script>
    <script src="{% static 'sms/scripts/signup_v3.js' %}"></script>
{% endblock body-internal-js %}

sms/templates/sms/require_password_change.html
{% extends 'base_generic.html' %}

{% load static %}

{% block content %}

    {% if password_change_failed %}
        <div class="loginErrorMessageDiv">密码变更失败，请再试一次。如您需要帮助，请联系我们。</div>
    {% endif %}

    {% if form.errors %}
        {% for key,value in form.errors.items %} 
            <div class="loginErrorMessageDiv">{{ value }}</div>
        {% endfor %}
    {% endif %}

    <div id="signupFormWrapper">
        <div id="loginFormCardTitle" class="d-flex justify-content-center align-items-center">
            <div></div>
        </div>
        <form class="loginForm" method="post" action="{% url 'require_password_change' %}">
        {% csrf_token %}
            <div class="loginInputDiv" id="password1InputDiv">
              <label for="{{ form.new_password1.id_for_label }}">新密码 </label>{{ form.new_password1 }}
            </div>
            <div class="loginInputDiv" id="password2InputDiv">
              <label for="{{ form.new_password2.id_for_label }}">确认新密码 </label>{{ form.new_password2 }}
            </div>
            <div>
              <button type="submit" class="loginPageButton">提交</button>
            </div>
        </form>
        <div id="loginFormLinktoSignup" class="d-flex justify-content-center align-items-center">
        </div>
    </div>

{% endblock %}

{% block body-internal-js %}{% endblock body-internal-js %}

sms/templates/sms/reset_password.html
{% extends 'base_generic.html' %}

{% load static %}

{% block content %}

    {% if password_change_failed %}
        <div class="loginErrorMessageDiv">密码变更失败，请再试一次。如您需要帮助，请联系我们。</div>
    {% endif %}

    {% if form.errors %}
        {% for key,value in form.errors.items %} 
            <div class="loginErrorMessageDiv">{{ value }}</div>
        {% endfor %}
    {% endif %}

    <div id="signupFormWrapper">
        <div id="loginFormCardTitle" class="d-flex justify-content-center align-items-center">
            <div></div>
        </div>
        <form class="loginForm" method="post" action="{% url 'reset_password_confirm' token=token_hex_str %}">
        {% csrf_token %}
            <div class="loginInputDiv" id="password1InputDiv">
              <label for="{{ form.new_password1.id_for_label }}">新密码 </label>{{ form.new_password1 }}
            </div>
            <div class="loginInputDiv" id="password2InputDiv">
              <label for="{{ form.new_password2.id_for_label }}">确认新密码 </label>{{ form.new_password2 }}
            </div>
            <div>
              <button type="submit" class="loginPageButton">提交</button>
            </div>
        </form>
        <div id="loginFormLinktoSignup" class="d-flex justify-content-center align-items-center">
        </div>
    </div>

{% endblock %}

{% block body-internal-js %}{% endblock body-internal-js %}

sms/templates/sms/reset_password_captcha.html
{% extends 'base_generic.html' %}

{% load static %}

{% block content %}

    {% if form.errors %}
        {% for key,value in form.errors.items %}
            {% if key == "mobile" %}
                <div class="loginErrorMessageDiv">手机号: {{ value }}</div>
            {% elif key == "captcha" %}
                <div class="loginErrorMessageDiv">验证码: {{ value }}</div>
            {% else %}
                <div class="loginErrorMessageDiv">{{key}}: {{ value }}</div>
            {% endif %}
        {% endfor %}
    {% endif %}

    <div id="signupFormWrapper">
        <div id="loginFormCardTitle" class="d-flex justify-content-center align-items-center">
            <div></div>
        </div>
        <form class="loginForm" method="post" action="{% url 'reset_password_captcha' %}">
        {% csrf_token %}
            <div class="loginInputDiv" id="loginFormUsernameDiv">
              <label for="{{ form.mobile.id_for_label }}">手机号 </label>{{ form.mobile }}
            </div>
            <div class="loginInputDiv" id="captchaDiv">
              <label for="{{ form.captcha.id_for_label }}">验证码 </label>{{ form.captcha }}
            </div>
            <div>
              <button type="submit" class="loginPageButton">确定</button>
            </div>
        </form>
        <div id="loginFormLinktoSignup" class="d-flex justify-content-center align-items-center">
            <div>已经有账号？<a href="{% url 'login'%}"><span>立即登录</span></a></div>
        </div>
    </div>

{% endblock %}

{% block body-internal-js %}
    <script>
        $(function() {
            document.getElementById('id_captcha_1').setAttribute('required', '');
            
            // Click-handler for the refresh-link
            $('img.captcha').click(function(){
                var $form = $(this).parents('form');
                var url = location.protocol + "//" + window.location.hostname + ":"
                          + location.port + "/captcha/refresh/";

                // Make the AJAX-call
                $.getJSON(url, {}, function(json) {
                    $form.find('input[name="captcha_0"]').val(json.key);
                    $form.find('img.captcha').attr('src', json.image_url);
                });

                return false;
            });
        });
    </script>
{% endblock body-internal-js %}

sms/templates/sms/reset_password_sms.html
{% extends 'base_generic.html' %}

{% load static %}

{% block content %}

    {% if sms_authentication_failed %}
        <div class="loginErrorMessageDiv">短信验证失败。请您确认您填写的手机号码，然后再获取一个新的验证码试一次。如您需要帮助，请联系我们。</div>
    {% endif %}

    {% if form.errors %}
        {% for key,value in form.errors.items %} 
            <div class="loginErrorMessageDiv">{{ value }}</div>
        {% endfor %}
    {% endif %}

    <div id="signupFormWrapper">
        <div id="loginFormCardTitle" class="d-flex justify-content-center align-items-center">
            <div></div>
        </div>
        <form class="loginForm" method="post" action="{% url 'reset_password_sms' token=token_hex_str %}">
        {% csrf_token %}
            <div class="studentInfoItem" id="signupMobile">
              <span>手机号码： </span>{{ mobile }}
            </div>
            <div class="loginInputDiv" id="smsVerificationCodeDiv">
              <label for="{{ form.verification_code.id_for_label }}">短信验证码 </label>{{ form.verification_code }}<div id="smsBtn">获取验证码</div>
            </div>
            <div>
              <button type="submit" class="loginPageButton">确认</button>
            </div>
        </form>
        <div id="loginFormLinktoSignup" class="d-flex justify-content-center align-items-center">
            <div>已经有账号？<a href="{% url 'login'%}"><span>立即登录</span></a></div>
        </div>
    </div>

{% endblock %}

{% block body-internal-js %}
    <script>var for_signup_django = false;</script>
    <script>var token_django = '{{token_hex_str}}';</script>
    <script src="{% static 'sms/scripts/signup_v3.js' %}"></script>
{% endblock body-internal-js %}

sms/templates/sms/signup.html
{% extends 'base_generic.html' %}

{% load static %}

{% block content %}

    {% if sms_authentication_failed %}
        <div class="loginErrorMessageDiv">短信验证失败。请您确认您填写的手机号码，然后再获取一个新的验证码试一次。如您需要帮助，请联系我们。</div>
    {% endif %}

    {% if form.errors %}
        {% for key,value in form.errors.items %} 
            <div class="loginErrorMessageDiv">{{ value }}</div>
        {% endfor %}
    {% endif %}

    <div id="signupFormWrapper">
        <div id="loginFormCardTitle" class="d-flex justify-content-center align-items-center">
            <div></div>
        </div>
        <form class="loginForm" method="post" action="{% url 'signup' %}">
        {% csrf_token %}
            <div class="loginInputDiv" id="loginFormUsernameDiv">
              <label for="{{ form.username.id_for_label }}">手机号 </label>{{ form.username }}
            </div>
            <div class="loginInputDiv" id="password1InputDiv">
              <label for="{{ form.password1.id_for_label }}">密码 </label>{{ form.password1 }}
            </div>
            <div class="loginInputDiv" id="password2InputDiv">
              <label for="{{ form.password2.id_for_label }}">确认密码 </label>{{ form.password2 }}
            </div>
            <div class="loginInputDiv" id="smsVerificationCodeDiv">
              <label for="{{ form.verification_code.id_for_label }}">短信验证码 </label>{{ form.verification_code }}<div id="smsBtn">获取验证码</div>
            </div>
            <div>
              <button type="submit" class="loginPageButton">注册</button>
            </div>
        </form>
        <div id="loginFormLinktoSignup" class="d-flex justify-content-center align-items-center">
            <div>已经有账号？<a href="{% url 'login'%}"><span>立即登录</span></a></div>
        </div>
    </div>

{% endblock %}

{% block js %}
    <script>var for_signup_django = true;</script>
    <script src="{% static 'sms/scripts/signup_v2.js' %}"></script>
{% endblock js %}

sms/templates/sms/signup_captcha.html
{% extends 'base_generic.html' %}

{% block content %}

    {% if mobile_already_registered %}
        <div class="loginErrorMessageDiv">此手机号码已经注册。</div>
    {% endif %}

    {% if form.errors %}
        {% for key,value in form.errors.items %}
            {% if key == "mobile" %}
                <div class="loginErrorMessageDiv">手机号: {{ value }}</div>
            {% elif key == "captcha" %}
                <div class="loginErrorMessageDiv">验证码: {{ value }}</div>
            {% else %}
                <div class="loginErrorMessageDiv">{{key}}: {{ value }}</div>
            {% endif %}
        {% endfor %}
    {% endif %}

    <div id="signupFormWrapper">
        <div id="loginFormCardTitle" class="d-flex justify-content-center align-items-center">
            <div></div>
        </div>
        <form class="loginForm" method="post" action="{% url 'signup' %}">
        {% csrf_token %}
            <div class="loginInputDiv" id="loginFormUsernameDiv">
              <label for="{{ form.mobile.id_for_label }}">手机号 </label>{{ form.mobile }}
            </div>
            <div class="loginInputDiv" id="captchaDiv">
              <label for="{{ form.captcha.id_for_label }}">验证码 </label>{{ form.captcha }}
            </div>
            <div>
              <button type="submit" class="loginPageButton">确定</button>
            </div>
        </form>
        <div id="loginFormLinktoSignup" class="d-flex justify-content-center align-items-center">
            <div>已经有账号？<a href="{% url 'login'%}"><span>立即登录</span></a></div>
        </div>
    </div>

{% endblock %}

{% block body-internal-js %}
    <script>
        $(function() {
            document.getElementById('id_captcha_1').setAttribute('required', '');
            
            // Click-handler for the refresh-link
            $('img.captcha').click(function(){
                var $form = $(this).parents('form');
                var url = location.protocol + "//" + window.location.hostname + ":"
                          + location.port + "/captcha/refresh/";

                // Make the AJAX-call
                $.getJSON(url, {}, function(json) {
                    $form.find('input[name="captcha_0"]').val(json.key);
                    $form.find('img.captcha').attr('src', json.image_url);
                });

                return false;
            });
        });
    </script>
{% endblock body-internal-js %}

sms/templates/sms/sms_request.html
{% extends 'base_generic.html' %}

{% load static %}

{% block content %}

    {% if sms_authentication_failed %}
        <div class="loginErrorMessageDiv">短信验证失败。请您确认您填写的手机号码，然后再获取一个新的验证码试一次。如您需要帮助，请联系我们。</div>
    {% endif %}

    {% if form.errors %}
        {% for key,value in form.errors.items %} 
            <div class="loginErrorMessageDiv">{{ value }}</div>
        {% endfor %}
    {% endif %}

    <div id="signupFormWrapper">
        <div id="loginFormCardTitle" class="d-flex justify-content-center align-items-center">
            <div></div>
        </div>
        <form class="loginForm" method="post" action="{% url 'request_sms_code' %}">
        {% csrf_token %}
            <div class="loginInputDiv" id="loginFormUsernameDiv">
              <label for="{{ form.mobile.id_for_label }}">手机号 </label>{{ form.mobile }}
            </div>
            <div class="loginInputDiv" id="smsVerificationCodeDiv">
              <label for="{{ form.verification_code.id_for_label }}">短信验证码 </label>{{ form.verification_code }}<div id="smsBtn">获取验证码</div>
            </div>
            <div>
              <button type="submit" class="loginPageButton">验证</button>
            </div>
        </form>
        <div id="loginFormLinktoSignup" class="d-flex justify-content-center align-items-center">
            <div>已经有账号？<a href="{% url 'login'%}"><span>立即登录</span></a></div>
        </div>
    </div>

{% endblock %}

{% block js %}
    <script>var for_signup_django = false;</script>
    <script src="{% static 'sms/scripts/signup_v2.js' %}"></script>
{% endblock js %}