gnwproject/urls.py
#import debug_toolbar
from django.conf.urls import url, include
from django.contrib import admin
from gnw import views as gnw_views
from sms import views as sms_views
from people import views as people_views
from django.urls import path


urlpatterns = [
    url(r'^ycchtliaaau/', admin.site.urls, name='admin-page'),
    url(r'^admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += [
    url(r'^$', gnw_views.index, name='index'),
    #url(r'^signup/$', sms_views.signup_captcha, name='signup'), Turned off since we are not allowing direct user signups
    #url(r'^signup/activate/(?P<token>\w+)/$', sms_views.activate_new_user, name='activate_new_user'),
    url(r'^panel/$', gnw_views.panel, name='panel'),
    url(r'^panel/update_my_info/$', people_views.update_student_info, name='update_student_info'),
    url(r'^panel/show_my_info/$', people_views.show_my_info, name='show_my_info'),
    url(r'^course/(?P<slug>[\w-]+)/$', gnw_views.course, name='class'),
    url(r'^course/(?P<slug>[\w-]+)/video/(?P<uuid>\d+)/$', gnw_views.video, name='video'),
    url(r'^course/(?P<slug>[\w-]+)/quiz/(?P<uuid>\d+)/$', gnw_views.quiz, name='quiz'),
    url(r'^course/(?P<slug>[\w-]+)/assignment/(?P<uuid>\d+)/$', gnw_views.assignment, name='assignment'),
]

urlpatterns += [
    url(r'^api/submit-photo-assignment/', gnw_views.submit_image_assignment, name='submit-photo-assignment'),
]

#Ajax to request sms sign-up verification
urlpatterns += [
    url(r'^ajax/request_sms/(?P<token>\w+)/$', sms_views.ajax_send_sms_verification_code, name='ajax_send_sms_verification_code'),
]

#Request sms verification for password reset, etc. 
urlpatterns += [
    url(r'^reset_password_request/$', sms_views.reset_password_captcha, name='reset_password_captcha'),
    url(r'^reset_password_sms/(?P<token>\w+)/$', sms_views.reset_password_sms, name='reset_password_sms'),
    url(r'^reset_password_confirm/(?P<token>\w+)/$', sms_views.reset_password_confirm, name='reset_password_confirm'),
    url(r'^require-password-change/$', sms_views.require_password_change, name='require_password_change'),
]

urlpatterns += [
    url(r'^progress/', include('progress.urls')),
]

urlpatterns += [
    url(r'^captcha/', include('captcha.urls')),
    #path('__debug__/', include(debug_toolbar.urls)),
]

progress/urls.py
from django.conf.urls import url
from progress import views

urlpatterns = [
    url(r'^ajax/record_completed_lesson/$', views.ajax_record_completed_lesson, name='record_completed_lesson'),
]

gnw/models.py
from pathlib import Path
from django.utils.crypto import get_random_string
from django.utils.text import slugify
from django.utils.timezone import now
from django.db import models
from django.core.exceptions import ValidationError
from django.conf import settings

#======================================================
#Course
#======================================================
class Course(models.Model):
    course_name = models.CharField(max_length = 200, unique=True)

    slug = models.SlugField(max_length = 200, unique=True, blank=True, help_text='Enter a URL-friendly course name without spaces and using only letters, digits, hypens, and underscores; leave it blank to auto generate from course name')

    is_public = models.BooleanField(default=False)

    def __str__(self):
        return self.course_name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.course_name)
        super().save(*args, **kwargs)

#======================================================
#Unit
#======================================================
class Unit(models.Model):
    course = models.ForeignKey(Course, on_delete=models.PROTECT)

    unit_name = models.CharField(max_length = 200)

    unit_number = models.PositiveIntegerField(blank=True, help_text="Do not change unless re-ordering units")
    
    class Meta:
        unique_together = (("course", "unit_name"), ("course", "unit_number"))

    def __str__(self):
        return self.course.course_name + " " + self.unit_name

    def generate_unit_order_number(self):
        last_unit = Unit.objects.filter(course=self.course).order_by('unit_number').last()
        if last_unit is not None:
            return last_unit.unit_number + 1
        else:
            return 1

    def save(self, *args, **kwargs):
        if not self.unit_number:
            self.unit_number = self.generate_unit_order_number()
        super().save(*args, **kwargs)

#======================================================
#Lesson
#======================================================
class Lesson(models.Model):
    unit = models.ForeignKey(Unit, on_delete=models.PROTECT)

    lesson_name = models.CharField(max_length = 200)

    lesson_number = models.PositiveIntegerField(blank=True, help_text="Do not change unless re-ordering lessons") 

    is_public = models.BooleanField(default=False)

    random_slug = models.CharField(max_length = 6, unique=True, blank=True, help_text="Leave blank to use system default")

    LESSON_TYPE_CHOICES = [
        ('VIDEO', 'Video'),
        ('QUIZ', 'Quiz'),
        ('ASSIGNMENT', 'Assignment'),
    ]

    lesson_type = models.CharField(max_length = 25, choices=LESSON_TYPE_CHOICES)

    #All possible formats of this lesson (choose at most one and leave the rest blank):
    #--------------------------------
    video = models.ForeignKey('Video', blank=True, null=True, on_delete=models.PROTECT)
    assignment_details = models.JSONField(blank=True, null=True)
    #--------------------------------

    def __str__(self):
        return self.unit.course.course_name + " Unit " + str(self.unit.unit_number) + " " + self.lesson_name

    def get_next_lesson(self):
        """
        Checks to see if there are more lessons in the same unit.
        If yes, then get the info needed to render that lesson on the front end;
        if no, then return the next lesson type as 'NONE'
        """
        next_lesson_in_unit = Lesson.objects.filter(unit=self.unit, lesson_number__gt=self.lesson_number).order_by('lesson_number').first()
        
        if next_lesson_in_unit is not None:
            next_lesson_id = next_lesson_in_unit.random_slug
            next_lesson_type = next_lesson_in_unit.lesson_type

            if next_lesson_type in ['VIDEO', 'QUIZ', 'ASSIGNMENT']:
                return {'next_lesson_id':next_lesson_id, 'next_lesson_type':next_lesson_type}
            #else: add other lesson types in the future
              
        else:
            next_lesson_type = 'NONE'
            return {'next_lesson_type':next_lesson_type}

    def get_quiz_questions_context_json(self):
        quiz_questions = self.quiz_question_set.values_list('properties', flat=True)
        return list(quiz_questions)

    def get_assignment_details_json(self):
        return self.assignment_details
            
    def clean(self):
        """
        Make sure each lesson has exactly one lesson type.
        This is called by ModelForm when saving through ModelForm (e.g. Admin site).
        Be sure to call full_clean() if creating or updating by calling save().
        """
        if self.lesson_type == 'VIDEO' and not self.video:
            raise ValidationError('Lesson Type = video, but you are not pointing it to a video.')
        elif self.lesson_type == 'QUIZ' and (self.video or self.assignment_details):
            raise ValidationError('Lesson Type = quiz, but you provided details for a video or an assignment.')
        elif self.lesson_type == 'ASSIGNMENT' and not self.assignment_details:
            raise ValidationError('Lesson Type = assignment, but you left the assignment details blank.')

    def generate_lesson_order_number(self):
        last_lesson = Lesson.objects.filter(unit=self.unit).order_by('lesson_number').last()
        if last_lesson is not None:
            return last_lesson.lesson_number + 1
        else:
            return 1

    @classmethod
    def random_id_generator(cls):
        while True:
            lesson_id = get_random_string(6, '0123456789')
            if not cls.objects.filter(random_slug=lesson_id).exists():
                break
        return lesson_id

    def save(self, *args, **kwargs):
        if not self.lesson_number:
            self.lesson_number = self.generate_lesson_order_number()
        if not self.random_slug:
            self.random_slug = Lesson.random_id_generator()
        super().save(*args, **kwargs)

    class Meta:
        unique_together = (("unit", "lesson_name"), ("unit", "lesson_number"))

#======================================================
#Video
#======================================================
class Video(models.Model):
    video_file_name = models.CharField(max_length = 200, default="")
    properties = models.JSONField(blank=True, null=True)
    
    def __str__(self):
        return self.video_file_name

    def get_video_questions_context_json(self):
        return self.properties


#======================================================
#Quiz_Question
#====================================================== 
class Quiz_Question(models.Model):
    lesson = models.ManyToManyField(Lesson)
    question_name = models.CharField(max_length = 200, help_text="This is what comes up in database search results. It does not appear in the actual quiz question.")
    properties = models.JSONField(blank=True, null=True)

    def __str__(self):
        return self.question_name


#======================================================
#Assignment
#====================================================== 
class Assignment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    lesson = models.ForeignKey(Lesson, on_delete=models.PROTECT)

    submitted_time = models.DateTimeField(default=now, help_text="Leave blank to use system default") 

    graded = models.BooleanField(default=False)

    graded_time = models.DateTimeField(blank=True, null=True, help_text="Leave blank to use system default")

    properties = models.JSONField(blank=True, null=True, help_text="Leave blank for now")

    image1 = models.ImageField()
    image2 = models.ImageField(blank=True, null=True)
    image3 = models.ImageField(blank=True, null=True)
    image4 = models.ImageField(blank=True, null=True)
    image5 = models.ImageField(blank=True, null=True)
    image6 = models.ImageField(blank=True, null=True)
    image7 = models.ImageField(blank=True, null=True)
    image8 = models.ImageField(blank=True, null=True)
    
    def __str__(self):
        return "Assignment for: " + self.lesson.lesson_name

    def get_assignment_context_json(self):
        return self.properties

    def get_assignment_context(self):
        """
        This is used in the JS frontend. If the model is restructured to
        use json only, this method will not be needed anymore.
        """
        ctx = {}
        ctx['submitted_time'] = self.submitted_time
        ctx['graded'] = self.graded
        ctx['graded_time'] = self.graded_time

        if self.graded:
            ctx['photos'] = []
            for i in range(1,9):
                image = getattr(self, 'image'+str(i))
                if image.name:
                    ctx['photos'].append(image.url)
        return ctx

    def assign_unique_names_to_images(self):
        """
        When an assignment is submitted, the uploaded images are renamed with 
        random characters so that no accidental override happens.
        """
        for i in range(1,9):
            image = getattr(self, 'image'+str(i))
            if image.name:
                file_extension = Path(image.name).suffix
                image.name = get_random_string(12) + file_extension

    def save(self, *args, **kwargs):
        if self.graded and not self.graded_time:
            self.graded_time = now()
        super().save(*args, **kwargs)

gnw/forms.py
from django.forms import ModelForm, CharField
from gnw.models import Assignment

class Submitted_Assignment_Form(ModelForm):

    lesson_uuid = CharField(max_length=6, min_length=6)
    course_slug = CharField(max_length=200)

    class Meta:
        model = Assignment
        fields = [
            'image1',
            'image2',
            'image3',
            'image4',
            'image5',
            'image6',
            'image7',
            'image8'
            ]

gnw/templates/gnw/assignment.html
{% extends "base_lecture.html" %}

{% load static %}

{% csrf_token %}

{% block content %}
  <div id="exerciseArea">
      <div id="uploadBox" class="container-md mt-5">
        <div id="instructionsBox">
            <p>请完成上一节课的作业，然后拍照上传。</p>
            <p>最多可以上传<span style="color:red;">8</span>张照片。</p>
            <p>老师会在一周内批改作业，批改好的作业会上传到此页。</p>
        </div>
      </div>
    <div class="bottomBufferDiv"></div>
    <div class="" id="nextButtonBox">
        {% if next_lesson_type == 'VIDEO' %}
        <a href="{% url 'video' slug=course_slug uuid=next_lesson_id %}"><button class="nextLecture">Next</button></a>
        {% elif next_lesson_type == 'QUIZ' %}
        <a href="{% url 'quiz' slug=course_slug uuid=next_lesson_id %}"><button class="nextLecture">Next</button></a>
        {% elif next_lesson_type == 'ASSIGNMENT' %}
        <a href="{% url 'assignment' slug=course_slug uuid=next_lesson_id %}"><button class="nextLecture">Next</button></a>
        {% elif next_lesson_type == 'NONE' %}
        <a href="{% url 'class' slug=course_slug %}"><button class="nextLecture">Home</button></a>
        {% endif %}
    </div>
    <div class="bottomBufferDiv"></div>
  </div>
{% endblock content %}

{% block body-internal-js %}
        {{ assignment_details_dict|json_script:"assignment_details_dict" }}
        <script>
            let assignment_details = JSON.parse(document.getElementById('assignment_details_dict').textContent);
        </script>

        {% if assignment_submitted %}
          {{ submitted_assignment_details_dict|json_script:"submitted_assignment_details_dict" }}
          <script>
            let submitted_assignment_details = JSON.parse(document.getElementById('submitted_assignment_details_dict').textContent);
            let assignment_submitted = true;
          </script>
        {% else %}
          <script>
            let assignment_submitted = false;
            let course_slug = "{{course_slug}}";
          </script>
        {% endif %}

        <script>let lesson_js_signal = "ASSIGNMENT";</script>
        <script>
          let lesson_id = "{{lesson_id}}";
        </script>
        {{block.super}}
{% endblock body-internal-js %}

gnw/templates/gnw/course.html
{% extends "base_generic.html" %}

{% load static %}

{% block content %}
<section id="classLessonsSection">
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="classLessonsWrapper">
                    {% for unit in course.unit_set.all|dictsort:"unit_number" %}
                    
                        <div class="unitBlock">{{unit.unit_name}}</div>
                    
                        {% for lesson in unit.lesson_set.all|dictsort:"lesson_number" %}
                        
                            {% if lesson.lesson_type == 'VIDEO' %}
                                <a href="{% url 'video' slug=course_slug uuid=lesson.random_slug %}" class="lessonLink">
                                    <div class="lessonBlock">
                                        <div class="lessonIconContainer"><span class="lesson-number">{{forloop.counter}}</span></div>
                                        <div class="lessonTitleContainer">{{lesson.lesson_name}}</div>
                                        {% if lesson.random_slug in completed_Lessons %}
                                            <div class="lesson-completed-check ml-auto align-self-center"></div>
                                        {% else %}
                                            <div class="lesson-circle ml-auto align-self-center"></div>
                                        {% endif %}
                                    </div>
                                </a>
                            {% elif lesson.lesson_type == 'QUIZ' %}
                                <a href="{% url 'quiz' slug=course_slug uuid=lesson.random_slug %}" class="lessonLink">
                                    <div class="lessonBlock">
                                        <div class="lessonIconContainer"><span class="lesson-number">{{forloop.counter}}</span></div>
                                        <div class="lessonTitleContainer">{{lesson.lesson_name}}</div>
                                        {% if lesson.random_slug in completed_Lessons %}
                                            <div class="lesson-completed-check ml-auto align-self-center"></div>
                                        {% else %}
                                            <div class="lesson-circle ml-auto align-self-center"></div>
                                        {% endif %}
                                    </div>
                                </a>
                            {% elif lesson.lesson_type == 'ASSIGNMENT' %}
                                <a href="{% url 'assignment' slug=course_slug uuid=lesson.random_slug %}" class="lessonLink">
                                    <div class="lessonBlock">
                                        <div class="lessonIconContainer"><span class="lesson-number">{{forloop.counter}}</span></div>
                                        <div class="lessonTitleContainer">{{lesson.lesson_name}}</div>
                                        {% if lesson.random_slug in completed_Lessons %}
                                            <div class="lesson-completed-check ml-auto align-self-center"></div>
                                        {% else %}
                                            <div class="lesson-circle ml-auto align-self-center"></div>
                                        {% endif %}
                                    </div>
                                </a>
                            {% endif %}
                            
                        {% endfor %}
                    
                    {% endfor %}
                    
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

{% block body-internal-js %}
    <script>let lesson_js_signal = "COURSE MENU";</script>
    {{block.super}}
{% endblock body-internal-js %}

gnw/templates/gnw/index.html
{% extends "base_generic.html" %}

{% load static %}

{% block content %}

<div id="coverImageContainer">
    <img src="{% static 'gnw/img/frontpagecoverimg.jpg' %}" class="img-fluid">
    <div id="boxOverCoverImage">
        <p id="coverTextTitle" class="mb-3">思惟、写作、逻辑课</p>
        <a href="{% url 'panel'%}" class="myLinkBtn coverCurriculumButton frontPageBtn">去上课</a>
    </div>
</div>

<section id="threeIconsRow">
    <div class="container">
        <div class="row">
            <div class="col-sm-4">
                <figure class="threeIconsRowFigure">
                    <img src="{% static 'gnw/img/frontpagegrammarimg.svg' %}">
                    <figcaption>思惟</figcaption>
                </figure>
            </div>
            <div class="col-sm-4">
                <figure class="threeIconsRowFigure">
                    <img src="{% static 'gnw/img/frontpagewritingimg.svg' %}">
                    <figcaption>写作</figcaption>
                </figure>
            </div>
            <div class="col-sm-4">
                <figure class="threeIconsRowFigure">
                    <img src="{% static 'gnw/img/frontpagethinkingimg.svg' %}">
                    <figcaption>逻辑</figcaption>
                </figure>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

{% block body-internal-js %}{% endblock body-internal-js %}

gnw/templates/gnw/panel.html
{% extends "base_generic.html" %}

{% load static %}

{% block content %}

{% if messages %}
    <div class="modal" id="firstVisitModal" tabindex="-1" role="dialog">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">飞猫星球</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
              {% for message in messages %}
                <p>{{message}}</p>
              {% endfor %}
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">关闭</button>
          </div>
        </div>
      </div>
    </div>
{% endif %}

<section id="enrolledClassesHeadingSection">
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <div id="enrolledClassesHeading">我的课程：</div>
            </div>
        </div>
    </div>
</section>
<section id="enrolledClassesContainerSection">
    <div class="container-fluid">
        <div class="row">
            <div class="col">
              <div class="mycard-deck">
                  {% for class in enrolled_classes %}
                  <a href="{% url 'class' slug=class.course.slug %}">
                      <div class="card mb-3">
                        <div class="row no-gutters">
                          <div class="col-3 bg-light">
                            {% if class.course.course_name|upper == "SYLLOGISM 1" %}
                              <img class="img-fluid" src="{% static 'gnw/img/venn_diagram.svg' %}">
                            {% elif class.course.course_name|upper == "LOGIC 101" %}
                              <img class="img-fluid" src="{% static 'gnw/img/venn_diagram.svg' %}">
                            {% elif class.course.course_name|upper == "LOGICAL FALLACIES: STRAW MAN" %}
                              <img class="img-fluid" src="{% static 'gnw/img/venn_diagram.svg' %}">
                            {% endif %}
                          </div>
                          <div class="col-9">
                            <div class="card-description">
                              <span class="mycard-title">{{ class.course.course_name }}</span>
                            </div>
                          </div>
                        </div>
                      </div>
                    </a>
                  {% endfor %}
              </div>
            </div>
        </div>
    </div>
</section>


{% endblock content %}

{% block body-internal-js %}

  {% if messages %}
      <script>
          $(document).ready(function(){
              $("#firstVisitModal").modal('show');
          });
      </script>
  {% endif %}

{% endblock body-internal-js %}

gnw/templates/gnw/quiz.html
{% extends "base_lecture.html" %}

{% load static %}

{% csrf_token %}

{% block content %}
  <div id="exerciseArea">
    <div class="bottomBufferDiv"></div>
    <div class="" id="nextButtonBox">
        {% if next_lesson_type == 'VIDEO' %}
        <a href="{% url 'video' slug=course_slug uuid=next_lesson_id %}"><button class="nextLecture">Next</button></a>
        {% elif next_lesson_type == 'QUIZ' %}
        <a href="{% url 'quiz' slug=course_slug uuid=next_lesson_id %}"><button class="nextLecture">Next</button></a>
        {% elif next_lesson_type == 'ASSIGNMENT' %}
        <a href="{% url 'assignment' slug=course_slug uuid=next_lesson_id %}"><button class="nextLecture">Next</button></a>
        {% elif next_lesson_type == 'NONE' %}
        <a href="{% url 'class' slug=course_slug %}"><button class="nextLecture">Home</button></a>
        {% endif %}
    </div>
    <div class="bottomBufferDiv"></div>
  </div>
{% endblock content %}

{% block body-internal-js %}
        {{ quiz_questions_list|json_script:"quiz_questions_list" }}
        <script>
            let mc_questions = JSON.parse(document.getElementById('quiz_questions_list').textContent);
        </script>
        <script>let lesson_js_signal = "QUIZ";</script>
        <script>
          let img_url = "{% static img_url %}";
          let audio_url = "{% static audio_url %}";
          let lesson_id = "{{lesson_id}}";
        </script>
        <script src="{% static 'gnw/scripts/audio-player_v_1_1.js' %}"></script>
        {{block.super}}
{% endblock body-internal-js %}

gnw/templates/gnw/video.html
{% extends "base_lecture.html" %}

{% load static %}

{% csrf_token %}

{% block content %}
    <div id="exerciseArea">
        <div id="videoBox">
            <div class="playback-animation" id="playback-animation">
                <svg class="playback-icons">
                  <use class="hidden" href="#play-icon"></use>
                  <use href="#pause"></use>
                </svg>
            </div>
            <video id="myvideo" controls controlsList="nodownload" preload="auto">
                {% with video_url|add:video_name as video_file_url %}
                    <source src="{% static video_file_url %}" type="video/mp4">
                {% endwith %}
            </video>
            <div class="video-controls hidden" id="video-controls">
                <div class="video-progress">
                  <progress id="progress-bar" value="0" min="0"></progress>
                  <input class="seek" id="seek" value="0" min="0" type="range" step="1">
                  <div class="seek-tooltip" id="seek-tooltip">00:00</div>
                </div>
        
                <div class="bottom-controls">
                  <div class="left-controls">
                    <button data-title="Play" id="play">
                      <svg class="playback-icons">
                        <use href="#play-icon"></use>
                        <use class="hidden" href="#pause"></use>
                      </svg>
                    </button>
        
                    <div class="volume-controls">
                      <button data-title="Mute" class="volume-button" id="volume-button">
                        <svg>
                          <use class="hidden" href="#volume-mute"></use>
                          <use class="hidden" href="#volume-low"></use>
                          <use href="#volume-high"></use>
                        </svg>
                      </button>
        
                      <input class="volume" id="volume" value="1"
                      data-mute="0.5" type="range" max="1" min="0" step="0.01">
                    </div>
        
                    <div class="time">
                      <time id="time-elapsed">00:00</time>
                      <span> / </span>
                      <time id="duration">00:00</time>
                    </div>
                  </div>
        
                  <div class="right-controls">
                    <button data-title="Full screen" class="fullscreen-button" id="fullscreen-button">
                      <svg>
                        <use href="#fullscreen"></use>
                        <use href="#fullscreen-exit" class="hidden"></use>
                      </svg>
                    </button>
                  </div>
                </div>
            </div>
        </div>
        <div class="bottomBufferDiv"></div>
        <div class="" id="nextButtonBox">
            {% if next_lesson_type == 'VIDEO' %}
            <a href="{% url 'video' slug=course_slug uuid=next_lesson_id %}"><button class="nextLecture">Next</button></a>
            {% elif next_lesson_type == 'QUIZ' %}
            <a href="{% url 'quiz' slug=course_slug uuid=next_lesson_id %}"><button class="nextLecture">Next</button></a>
            {% elif next_lesson_type == 'ASSIGNMENT' %}
            <a href="{% url 'assignment' slug=course_slug uuid=next_lesson_id %}"><button class="nextLecture">Next</button></a>
            {% elif next_lesson_type == 'NONE' %}
            <a href="{% url 'class' slug=course_slug %}"><button class="nextLecture">Home</button></a>
            {% endif %}
        </div>
        <div class="bottomBufferDiv"></div>
    </div>

    <svg style="display: none">
        <defs>
          <symbol id="pause" viewBox="0 0 24 24">
            <path d="M14.016 5.016h3.984v13.969h-3.984v-13.969zM6 18.984v-13.969h3.984v13.969h-3.984z"></path>
          </symbol>
    
          <symbol id="play-icon" viewBox="0 0 24 24">
            <path d="M8.016 5.016l10.969 6.984-10.969 6.984v-13.969z"></path>
          </symbol>
    
          <symbol id="volume-high" viewBox="0 0 24 24">
          <path d="M14.016 3.234q3.047 0.656 5.016 3.117t1.969 5.648-1.969 5.648-5.016 3.117v-2.063q2.203-0.656 3.586-2.484t1.383-4.219-1.383-4.219-3.586-2.484v-2.063zM16.5 12q0 2.813-2.484 4.031v-8.063q1.031 0.516 1.758 1.688t0.727 2.344zM3 9h3.984l5.016-5.016v16.031l-5.016-5.016h-3.984v-6z"></path>
          </symbol>
    
          <symbol id="volume-low" viewBox="0 0 24 24">
          <path d="M5.016 9h3.984l5.016-5.016v16.031l-5.016-5.016h-3.984v-6zM18.516 12q0 2.766-2.531 4.031v-8.063q1.031 0.516 1.781 1.711t0.75 2.32z"></path>
          </symbol>
    
          <symbol id="volume-mute" viewBox="0 0 24 24">
          <path d="M12 3.984v4.219l-2.109-2.109zM4.266 3l16.734 16.734-1.266 1.266-2.063-2.063q-1.547 1.313-3.656 1.828v-2.063q1.172-0.328 2.25-1.172l-4.266-4.266v6.75l-5.016-5.016h-3.984v-6h4.734l-4.734-4.734zM18.984 12q0-2.391-1.383-4.219t-3.586-2.484v-2.063q3.047 0.656 5.016 3.117t1.969 5.648q0 2.203-1.031 4.172l-1.5-1.547q0.516-1.266 0.516-2.625zM16.5 12q0 0.422-0.047 0.609l-2.438-2.438v-2.203q1.031 0.516 1.758 1.688t0.727 2.344z"></path>
          </symbol>
    
          <symbol id="fullscreen" viewBox="0 0 24 24">
          <path d="M14.016 5.016h4.969v4.969h-1.969v-3h-3v-1.969zM17.016 17.016v-3h1.969v4.969h-4.969v-1.969h3zM5.016 9.984v-4.969h4.969v1.969h-3v3h-1.969zM6.984 14.016v3h3v1.969h-4.969v-4.969h1.969z"></path>
          </symbol>
    
          <symbol id="fullscreen-exit" viewBox="0 0 24 24">
          <path d="M15.984 8.016h3v1.969h-4.969v-4.969h1.969v3zM14.016 18.984v-4.969h4.969v1.969h-3v3h-1.969zM8.016 8.016v-3h1.969v4.969h-4.969v-1.969h3zM5.016 15.984v-1.969h4.969v4.969h-1.969v-3h-3z"></path>
          </symbol>
        </defs>
    </svg>
{% endblock content %}

{% block body-internal-js %}
        {{ video_questions_list|json_script:"video_questions_list" }}
        <script>
            let video_questions = JSON.parse(document.getElementById('video_questions_list').textContent);
        </script>
        <script>let lesson_js_signal = "VIDEO";</script>
        <script>
            let img_url = "{% static img_url %}";
            let lesson_id = "{{lesson_id}}";
        </script>
        <script src="{% static 'gnw/scripts/videoplayer_v_1_14.js' %}"></script>
        {{block.super}}
{% endblock body-internal-js %}